### PR TITLE
Cobalt 348

### LINKED ISSUE #348: Single line string literal is parsed incorrectly
String with single double quotes is meant to be single line. As seen in `testStringLiteralUnfinishedDoubleLineFail` the string:

```
"first line     
 second line"
```

Is successfuly parsed and produces.
`"first line \n second line"`

This might cause problems beause as seen in test `testStringLiteralUnfinishedDoubleLineLeadingWhitespaceFail` the leading whitespace which depends on the context of surrounding code is also parsed and preserved into string literal.

### PR DESCRIPTION
**Pull request by FilipJanitor**
Closes #348 
Since I needed to test parser failing on incorrect input, I implemented a temporary method to do so efficiently but without any info about what actually failed.

### CODE REVIEW

File: compiler/src/cobalt/Parser/Parser.hs [hunk 1]
```diff
@@ -390,8 +390,12 @@ statementBlockParser = BlockStmt <$> some statementParser
 
 stringLiteralParser :: Parser Stmt
 stringLiteralParser = do
-    value <- char '"' >> manyTill L.charLiteral (char '"')
+    value <- char '"' >> manyTill r (char '"')
     return $ StringLiteral value
+  where
+    r = label "valid char literal" $ do
```
Comment (Michael2109) [inline compiler/src/cobalt/Parser/Parser.hs]: Should this instead be `Invalid char literal`? Looking it up `label` displays the string upon the parser failing.

**Review by Michael2109 — DISMISSED** [review]
I've looked through this and it all looks great! Feel free to merge it when the checks are complete.

**Review by Michael2109 — APPROVED** [review]
